###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.5"
services:

    webserver:
      image: nginx:1.19.6-alpine
      container_name: gw-account-cmangos
      restart: unless-stopped
      volumes:
          - ./:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      networks:
       - backend-account-service

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm-account-cmangos
      restart: unless-stopped
      working_dir: /var/www
      # command: bash -c "chmod -R 777 storage bootstrap"
      volumes:
        - ./:/var/www:rw
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
       - backend-account-service
    
    composer:
      image: composer:2.0.8
      command: bash -c "composer require fruitcake/laravel-cors --ignore-platform-reqs"
      # command: bash -c "composer update --ignore-platform-reqs"
      # command: ["composer", "update", "--ignore-platform-reqs"]
      # command: bash -c "composer update --ignore-platform-reqs && composer create-project --prefer-dist laravel/lumen api" # ONETIME-use to create a first LUMEN project
      volumes:
        - .:/app
      networks:
       - backend-account-service

networks:
  backend-account-service:
    external:
      name: backend_network
