<script>
	import 'bulma/css/bulma.css'
	import { Button, Field, Icon, Input } from 'svelma'

	let bound = {
    name: '',
    password: '',
  }
</script>

<main class="columns is-full is-desktop is-centered">

	<div class="column is-one-third">
		<h1 class="title">Account creation</h1>
		<form>
			<Field>
				<Input class="is-medium" placeholder="Account name" icon="user" bind:value={bound.name} />
			</Field>

			<div class="field">
				<Input disabled class="is-medium" placeholder="Password" icon="key" value={bound.name ? bound.name + '12' : ''} />
				<div class="help is-warning" style="text-align: left;">Password is autogenerated from account name</div>
			</div>

			<button class="button is-primary is-fullwidth is-medium" type="is-primary">Create account</button>
			<br />
			<small><em>Lorem ipsum dolor sit amet consectetur.</em></small>
		</form>


	</div>
</main>

<style>

	/* a {
		color: #ffcf00;
		color: red;
		text-decoration: none;
	} */

	main {
		text-align: center;
		margin-top: 200px;
		/* margin: 0 auto; */
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 2em;
		font-weight: 100;
	}

</style>