<script>
	import 'bulma/css/bulma.css'
	import { Field, Icon, Input, Toast } from 'svelma'
	import { createForm } from 'svelte-forms-lib'
	import * as yup from 'yup'

	// const API_ACCOUNT_URL = process.env.isProd ? 'https://accountapi.wow.zhoply.com' : 'http://localhost:8080';
	const API_ACCOUNT_URL = 'http://accountapi.wow.zhoply.com';

	let isAcccountCreated = false
	
	function toastDisplay(type, message, position) {
    Toast.create({ message, type, position })
  }

	async function doPost (input) {
		const res = await fetch(`${API_ACCOUNT_URL}/register`, {
			headers: { 'Content-Type': 'application/json' },
			method: 'POST',
			body: JSON.stringify({
				...input // backend takes care of validation and injections...
			})
		})
		return { json: await res.json(), status: res.status }
	}

	const { form, errors, state, handleChange, handleSubmit, isSubmitting, validateField } = createForm({
		initialValues: {
			username: '',
			password: ''
		},
		validationSchema: yup.object().shape({
			username: yup
					.string()
					.min(2, 'Min characters is 2')
          .required('Username required'), // Username available
			password: yup
				.string()
				.required()
		}),
		onSubmit: values => {
			// console.log('submit: ', JSON.stringify(values));
			return doPost(values).then(res => {
				// Handle CONTROLLED errors like username taken etc..
				if (res.status != 200) {
					// console.log('ERROR : ', res);
					// console.log('errors : ', $errors);
					// Map errors(by keys) from backend to the svelte error-state keys
					Object.keys(res.json).map(errorKey => $errors[errorKey] = res.json[errorKey])
				} else {
					console.log('OK 200: ', res);
					toastDisplay('is-success', 'Account created!')
					isAcccountCreated = true
				}
			}).catch((error) => {
				// Handle uncontrolled errors, how to deal with these?
				console.error('Error!!:', error);
				toastDisplay('is-danger', error)
			});
		}
	})

	const computeUsernameChange = () => {
		// Re-validates and computes the password

		validateField('username')
		$form.password = $form.username ? $form.username + '12' : ''
	}

	console.log('API_ACCOUNT_URL :>> ', API_ACCOUNT_URL);
</script>

<main class="columns is-mobile is-centered">

	<div class="column is-8" style="max-width: 400px;">
		{#if isAcccountCreated}
			<h1 class="title">Account details</h1>
			<div style="text-align: left;">
				<table class="table is-fullwidth" style="opacity: 0.8;border-radius: 4px">
					<thead>
						<tr>
							<th></th>
							<th>Username</th>
							<th>Password</th>
						</tr>
					</thead>
					<tbody>
							<tr>
								<td></td>
								<td><Icon icon="user" /> {$form.username}</td>
								<td><Icon icon="key" /> {$form.password}</td>
							</tr>
					</tbody>
				</table>
			</div>
			<br />
			<br />
			<h1 class="title">Get started</h1>
			<ol style="text-align: left;">
				<li>Inside your World of Warcraft root folder, locate the "realmlist.wtf" file.</li>
				<li>Edit the file contents with a text editor to:<br />"set realmlist <strong>logon.wow.zhoply.com"</strong><br />
					(without quotes) and save the file.</li>
				<li>Start the game using Wow.exe.</li>
				<li>Log in using your created account name.</li>
			</ol>
		{:else}

			<h1 class="title">Account creation</h1>
			<form on:submit={handleSubmit}>
				<Field type={$errors.username ? 'is-danger' : ''} message={$errors.username ? $errors.username : ''} style="text-align: left;">
					<Input class="is-medium" placeholder="Account name" icon="user" name="username" on:input={computeUsernameChange} on:change={computeUsernameChange} bind:value={$form.username} />
				</Field>

				<Field message="Password is autogenerated from account name" style="text-align: left;">
					<Input class="is-medium" placeholder="Account name" icon="key" name="password" bind:value={$form.password} />
				</Field>

				<button disabled={!$form.password} class="button is-primary is-fullwidth is-medium" type="is-primary">
					
					{#if $isSubmitting}
						Creating account...
					{:else}
						Create account
					{/if}
				</button>
				<br />

				<!-- TODO => insert uncontrolled errors here <small><em>Lorem ipsum dolor sit amet consectetur.</em></small> -->
			</form>

		{/if}

	</div>
</main>

<style>

	/* a {
		color: #ffcf00;
		color: red;
		text-decoration: none;
	} */

	main {
		text-align: center;
		margin-top: 200px;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 2em;
		font-weight: 100;
	}

</style>