<script>
	import 'bulma/css/bulma.css'
	import { Button, Field, Icon, Input } from 'svelma'
	import { createForm } from 'svelte-forms-lib'
	import * as yup from 'yup'

	async function doPost (input) {
		const res = await fetch('http://localhost:8080/register', {
			headers: { 'Content-Type': 'application/json' },
			method: 'POST',
			body: JSON.stringify({
				...input // backend takes care of validation and injections...
			})
		})
		return { json: await res.json(), status: res.status }
	}

	const { form, errors, state, handleChange, handleSubmit, validateField,  } = createForm({
		initialValues: {
			username: '',
			password: ''
		},
		validationSchema: yup.object().shape({
			username: yup
					.string()
					.min(2, 'Min characters is 2')
          .required('Username required'), // Username available
			password: yup
				.string()
				.required()
		}),
		onSubmit: values => {
			// console.log('submit: ', JSON.stringify(values));
			doPost(values).then(res => {
				// Handle CONTROLLED errors like username taken etc..
				if (res.status != 200) {
					// console.log('ERROR : ', res);
					// console.log('errors : ', $errors);
					// Map errors(by keys) from backend to the svelte error-state keys
					Object.keys(res.json).map(errorKey => $errors[errorKey] = res.json[errorKey])
				} else {
					console.log('OK 200: ', res);
					// TODO => route do diffrent success page
				}
			}).catch((error) => {
				// Handle uncontrolled errors, how to deal with these?
				console.error('Error:', error);
			});
		}
	})

	const computeUsernameChange = () => {
		// Re-validates and computes the password
		validateField('username')
		$form.password = $form.username ? $form.username + '12' : ''
	}

</script>

<main class="columns is-mobile is-centered">

	<div class="column is-8" style="max-width: 400px;">
		<h1 class="title">Account creation</h1>
		{#if $errors.username}
      <small>{$errors.username}</small>
    {/if}
		<form on:submit={handleSubmit}>
			<Field type={$errors.username ? 'is-danger' : ''} message={$errors.username ? $errors.username : ''} style="text-align: left;">
				<Input class="is-medium" placeholder="Account name" icon="user" name="username" on:input={computeUsernameChange} on:change={computeUsernameChange} bind:value={$form.username} />
			</Field>

			<Field message="Password is autogenerated from account name" style="text-align: left;">
				<Input class="is-medium" placeholder="Account name" icon="key" name="password" bind:value={$form.password} />
			</Field>

			<button disabled={!$form.password} class="button is-primary is-fullwidth is-medium" type="is-primary">Create account</button>
			<br />
			<!-- TODO => insert uncontrolled errors here <small><em>Lorem ipsum dolor sit amet consectetur.</em></small> -->
		</form>

	</div>
</main>

<style>

	/* a {
		color: #ffcf00;
		color: red;
		text-decoration: none;
	} */

	main {
		text-align: center;
		margin-top: 200px;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 2em;
		font-weight: 100;
	}

</style>