###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: gw-account-cmangos
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm-account-cmangos
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    # composer:
    #   build: .
    #   container_name: composer
    #   tty: true

    composer:
      image: composer:2.0.8
      command: bash -c "composer update --ignore-platform-reqs"
      # command: ["composer", "update", "--ignore-platform-reqs"]
      # command: bash -c "composer update --ignore-platform-reqs && composer create-project --prefer-dist laravel/lumen api" # ONETIME-use to create a first LUMEN project
      volumes:
        - .:/app
